services:
  clip-server:
    build: ./clip-server
    restart: always
    environment:
      PORT: 5656
    volumes:
      - clipcache:/home/user/.cache
  bot1:
    build: ./bot
    restart: always
    environment:
      CLIP_URL: "http://clip-server:5656"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT1_TOKEN}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
  bot2:
    build: ./bot
    restart: always
    environment:
      CLIP_URL: "http://clip-server:5656"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT2_TOKEN}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}

volumes:
  clipcache:
