name: "Deploy"
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - name: Deploy to server
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      env:
        DOTENV: ${{ secrets.DEPLOY_DOTENV }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        last_ssh: |
          cd /home/deploy/SemanticStickers
          echo $DEPLOY_DOTENV > .env
          echo "Dotenv file updated"
          echo "Git pulling..."
          git pull
          echo "Compose build..."
          docker compose build
          echo "Compose up..."
          docker compose up -d
