name: "Deploy"
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      env:
        DOTENV: ${{ secrets.DEPLOY_DOTENV }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        envs: DOTENV
        script: |
          cd /home/deploy/SemanticStickers
          echo "$DOTENV" > .env
          echo "Dotenv file updated"
          echo "Git pulling..."
          git pull
          echo "Compose build..."
          docker compose build
          echo "Compose up..."
          docker compose up -d --remove-orphans
